name: Docker Workflow
on:
  push:
    branches:
    - master

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    name: Build and Publish Docker Image
    timeout-minutes: 20
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Set container name
        run: echo "::set-env name=CONTAINER_NAME::timber" # Change this to change the name of the package
      - name: Set lowercase repo env variable
        shell: python
        run: print("::set-env name=LOWER_REPO::{}".format('${{github.repository}}'.lower()))
      - name: Build Docker
        run: |
          secret_key_base="$(openssl rand -base64 32)"
          docker build  --build-arg secret_key_base="$secret_key_base" -t docker.pkg.github.com/${LOWER_REPO}/${CONTAINER_NAME}:latest .
      - name: Push the image to GPR
        run: |
          docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
          docker push docker.pkg.github.com/${LOWER_REPO}/${CONTAINER_NAME}:latest
          # Also push by SHA
          docker tag docker.pkg.github.com/${LOWER_REPO}/${CONTAINER_NAME}:latest docker.pkg.github.com/${LOWER_REPO}/${CONTAINER_NAME}:${{github.sha}}
          docker push docker.pkg.github.com/${LOWER_REPO}/${CONTAINER_NAME}:${{github.sha}}
        env:
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}